apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  nodeSelector:
    agentpool: pool1
  containers:
  - image: nginx:latest
    name: nginx-pod
    ports:
    - containerPort: 80
 