apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: default
  labels:
    app: nginx
spec:
  nodeName: aks-default-33048716-vmss00000b
  containers:
  - image: nginx:latest
    name: nginx-pod
    ports:
    - containerPort: 80
