apiVersion: v1
kind: PersistentVolume
metadata:
  name: amit-pv
  namespace: default
  labels:
    type: azurefile
spec:
  storageClassName: azurefile
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: sceretshare
    secretNamespace: default
    readOnly: false
