apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amit-pvc
  namespace: default
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # selector:
  #   matchLabels:
  #     type: azurefile
  # storageClassName: azurefile