apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
parameters:
  storageAccount: yup10
  secretName: azure-secret
  resourceGroup: merg
provisioner: file.csi.azure.com
reclaimPolicy: Retain
